import { useState, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { X } from 'lucide-react';
import { getGlobalLedger } from '../firebase/customers';
import { useToast } from '../context/ToastContext';
import { formatDateIST } from '../utils/dateIST';

const PAGE_SIZE = 20;

const cleanDesc = (e) => {
  if (e.type === 'sale') return 'Sale';
  if (e.type === 'opening') return 'Opening balance';
  if (e.type === 'payment') {
    if (e.autoGenerated) return 'Excess payment adjusted';
    return e.mode ? `Payment · ${e.mode}` : 'Payment';
  }
  return e.desc || '—';
};

const toDateObj = (timestamp) => {
  if (!timestamp) return null;
  const d = timestamp.toDate ? timestamp.toDate() : new Date(timestamp);
  return isNaN(d.getTime()) ? null : d;
};

// Calendar day (UTC) of an entry as 'YYYY-MM-DD' — matches how dates are stored
// (UTC midnight) and lets us string-compare against the date-picker values directly.
const dayStr = (timestamp) => {
  const d = toDateObj(timestamp);
  if (!d) return '';
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
};

const formatDate = (timestamp) => formatDateIST(timestamp);

export default function Ledger() {
  const navigate = useNavigate();
  const { showToast } = useToast();

  const [entries, setEntries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [currentPage, setCurrentPage] = useState(1);
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');

  useEffect(() => {
    const load = async () => {
      try {
        const data = await getGlobalLedger();
        setEntries(data);
      } catch (err) {
        console.error("Error loading global ledger:", err);
        showToast("Failed to load ledger", "error");
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  // Filtering is display-only: entries keep their true global running balance
  // (computed across ALL history), so a filtered range still shows real balances
  // at each row, exactly like a bank statement filtered to a period.
  const filteredEntries = useMemo(() => {
    if (!fromDate && !toDate) return entries;
    
    let opBal = 0;
    if (fromDate) {
      const prevEntry = entries.find(e => dayStr(e.date) < fromDate);
      opBal = prevEntry ? Number(prevEntry.globalBalanceAfter) : 0;
    }
    
    const items = entries.filter(e => {
      const day = dayStr(e.date);
      if (!day) return false;
      if (fromDate && day < fromDate) return false;
      if (toDate && day > toDate) return false;
      return true;
    });

    let clBal = opBal;
    if (items.length > 0) {
      clBal = Number(items[0].globalBalanceAfter) || 0;
    } else if (toDate) {
      const prev = entries.find(e => dayStr(e.date) <= toDate);
      clBal = prev ? Number(prev.globalBalanceAfter) : 0;
      opBal = clBal;
    }

    const openingRow = {
      id: 'synthetic-opening',
      isSynthetic: true,
      desc: 'Opening Balance for period',
      globalBalanceAfter: opBal,
      customerName: '—',
      date: fromDate ? new Date(fromDate) : (items.length > 0 ? items[items.length - 1].date : new Date())
    };

    const closingRow = {
      id: 'synthetic-closing',
      isSynthetic: true,
      desc: 'Closing Balance for period',
      globalBalanceAfter: clBal,
      customerName: '—',
      date: toDate ? new Date(toDate) : (items.length > 0 ? items[0].date : new Date())
    };

    return [closingRow, ...items, openingRow];
  }, [entries, fromDate, toDate]);

  // Reset to first page whenever the filter changes.
  useEffect(() => {
    setCurrentPage(1);
  }, [fromDate, toDate]);

  const isFiltered = !!(fromDate || toDate);
  const clearFilter = () => { setFromDate(''); setToDate(''); };

  // Net Balance is the current business-wide net outstanding — the newest overall
  // balance — independent of any date filter applied to the view below.
  const netBalance = entries.length > 0 ? Number(entries[0].globalBalanceAfter) || 0 : 0;
  const totalCount = filteredEntries.length;
  const start = (currentPage - 1) * PAGE_SIZE;
  const pageEntries = filteredEntries.slice(start, start + PAGE_SIZE);
  const startIdx = totalCount === 0 ? 0 : start + 1;
  const endIdx = Math.min(currentPage * PAGE_SIZE, totalCount);
  const isLastPage = endIdx >= totalCount;

  return (
    <div className="space-y-6">
      {/* Summary Card */}
      <div className="bg-white p-6 rounded-2xl shadow-sm border border-border flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="font-display text-2xl font-bold text-brownDark">Business Ledger</h2>
          <p className="text-textMuted text-sm mt-1">
            All customer sales and payments in one running statement.
          </p>
        </div>
        <div className="text-left sm:text-right">
          <p className="text-sm font-medium text-textMuted mb-1">Net Balance</p>
          <p className={`text-3xl font-bold ${netBalance > 0 ? 'text-debit' : 'text-textMuted'}`}>
            ₹{netBalance.toLocaleString('en-IN')}
          </p>
        </div>
      </div>

      {/* Date Filter */}
      <div className="bg-white p-4 rounded-xl shadow-sm border border-border flex flex-col sm:flex-row sm:items-end gap-3 sm:gap-4">
        <div className="flex-1">
          <label className="block text-xs font-medium uppercase tracking-wider text-textMuted mb-1">From</label>
          <input
            type="date"
            value={fromDate}
            max={toDate || undefined}
            onChange={(e) => setFromDate(e.target.value)}
            className="w-full px-3 py-2 rounded-lg border border-border bg-white text-sm text-textDark focus:outline-none focus:ring-2 focus:ring-gold/50 min-h-[44px]"
          />
        </div>
        <div className="flex-1">
          <label className="block text-xs font-medium uppercase tracking-wider text-textMuted mb-1">To</label>
          <input
            type="date"
            value={toDate}
            min={fromDate || undefined}
            onChange={(e) => setToDate(e.target.value)}
            className="w-full px-3 py-2 rounded-lg border border-border bg-white text-sm text-textDark focus:outline-none focus:ring-2 focus:ring-gold/50 min-h-[44px]"
          />
        </div>
        {isFiltered && (
          <button
            onClick={clearFilter}
            className="flex items-center justify-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium border border-border text-textDark hover:bg-panel/50 transition-colors min-h-[44px] whitespace-nowrap"
          >
            <X className="w-4 h-4" />
            Clear
          </button>
        )}
      </div>

      {/* Ledger Table */}
      <div className="bg-white rounded-xl shadow-sm border border-border overflow-hidden">
        <div className="overflow-x-auto max-h-[70vh]">
          <table className="w-full text-left border-collapse min-w-[760px]">
            <thead className="sticky top-0 z-10 bg-panel shadow-sm">
              <tr className="uppercase text-xs text-textMuted border-b border-border">
                <th className="py-3 px-6 font-medium">Date</th>
                <th className="py-3 px-6 font-medium">Customer</th>
                <th className="py-3 px-6 font-medium">Description</th>
                <th className="py-3 px-6 font-medium text-right">பற்று Debit</th>
                <th className="py-3 px-6 font-medium text-right">வரவு Credit</th>
                <th className="py-3 px-6 font-medium text-right">Balance</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="6" className="py-8 text-center text-textMuted text-sm">Loading ledger...</td>
                </tr>
              ) : pageEntries.length === 0 ? (
                <tr>
                  <td colSpan="6" className="py-8 text-center text-textMuted text-sm">
                    {isFiltered ? 'No entries in the selected date range.' : 'No ledger entries found.'}
                  </td>
                </tr>
              ) : (
                pageEntries.map(entry => {
                  if (entry.isSynthetic) {
                    return (
                      <tr
                        key={entry.id}
                        className="border-b border-border bg-panel/30 transition-colors"
                      >
                        <td className="py-3 px-6 text-sm text-textMuted whitespace-nowrap">{formatDate(entry.date)}</td>
                        <td className="py-3 px-6 text-sm font-medium text-textDark text-center">—</td>
                        <td className="py-3 px-6 text-sm font-bold text-textDark">{entry.desc}</td>
                        <td className="py-3 px-6 text-sm text-right font-medium text-debit">—</td>
                        <td className="py-3 px-6 text-sm text-right font-medium text-credit">—</td>
                        <td className="py-3 px-6 text-sm text-right font-bold text-brownDark">
                          {Number(entry.globalBalanceAfter || 0) < 0
                            ? `-₹${Math.abs(Number(entry.globalBalanceAfter || 0)).toLocaleString('en-IN')}`
                            : `₹${Number(entry.globalBalanceAfter || 0).toLocaleString('en-IN')}`
                          }
                        </td>
                      </tr>
                    );
                  }

                  return (
                  <tr
                    key={`${entry.customerId}-${entry.id}`}
                    onClick={() => navigate(`/customers/${entry.customerId}`)}
                    className="border-b border-border hover:bg-panel/50 transition-colors cursor-pointer"
                  >
                    <td className="py-3 px-6 text-sm text-textMuted whitespace-nowrap">{formatDate(entry.date)}</td>
                    <td className="py-3 px-6 text-sm font-medium text-textDark">{entry.customerName}</td>
                    <td className="py-3 px-6 text-sm text-textMuted">
                      <span className={entry.autoGenerated ? 'italic' : ''}>{cleanDesc(entry)}</span>
                    </td>
                    <td className="py-3 px-6 text-sm text-right font-medium text-debit">
                      {Number(entry.debit) > 0 ? `₹${Number(entry.debit).toLocaleString('en-IN')}` : '—'}
                    </td>
                    <td className="py-3 px-6 text-sm text-right font-medium text-credit">
                      {Number(entry.credit) > 0 ? `₹${Number(entry.credit).toLocaleString('en-IN')}` : '—'}
                    </td>
                    <td className="py-3 px-6 text-sm text-right font-bold text-textDark">
                      {Number(entry.globalBalanceAfter || 0) < 0
                        ? `-₹${Math.abs(Number(entry.globalBalanceAfter || 0)).toLocaleString('en-IN')}`
                        : `₹${Number(entry.globalBalanceAfter || 0).toLocaleString('en-IN')}`
                      }
                    </td>
                  </tr>
                )})
              )}
            </tbody>
          </table>
        </div>
        {!loading && totalCount > 0 && (
          <div className="flex items-center justify-between p-4 border-t border-border bg-panel/30">
            <button
              onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
              disabled={currentPage <= 1}
              className="px-4 py-2 rounded-lg text-sm font-medium border border-border bg-white text-textDark hover:bg-gold/10 disabled:opacity-50 disabled:pointer-events-none transition-colors"
            >
              ← Newer
            </button>
            <span className="text-xs text-textMuted font-medium">
              Showing {startIdx}–{endIdx} of {totalCount} entries
            </span>
            <button
              onClick={() => setCurrentPage(p => p + 1)}
              disabled={isLastPage}
              className="px-4 py-2 rounded-lg text-sm font-medium border border-border bg-white text-textDark hover:bg-gold/10 disabled:opacity-50 disabled:pointer-events-none transition-colors"
            >
              Older →
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
